### ISSUE TITLE
When creating an account, and you sign in, and you mistype the password, you're redirected to reset-password instantly

### ISSUE THREAD

**Issue by Portals** [cthit/Gamma#551] opened 2020-02-19 16:55 UTC

**Comment by Gurr1** [comment] 2020-02-23 19:59
cannot reproduce this error, which commit is ITUser.java on, and does V.1.2__user_activated_account.sql exist?

**Comment by Gurr1** [comment] 2020-03-02 18:30
I'm closing this, it was fixed on V1.2 of the database

**Closed by Gurr1** 2020-03-02 18:30 UTC
Labels: Priority: Critical, Status: On Hold
