### ISSUE TITLE
Add image to group and suppergroups

### ISSUE THREAD

**Issue by ericlp** [cthit/Gamma#774] opened 2020-10-16 12:57 UTC
Would be nice to show off how cool you are.

If a group does not have an image it should use the image of the supergroup.

**Comment by Portals** [comment] 2021-02-06 12:58
Sort of a duplicate of #731. Avatars for supergroups aren't really something that will be used. digIT is the only case where there's a reason for avatar for supergroups.

**Closed by Portals** 2021-02-06 12:58 UTC
