### ISSUE TITLE
Add ability to search for more than one thing when searching for users.

### ISSUE THREAD

**Issue by ViddeM** [cthit/Gamma#722] opened 2020-05-11 14:20 UTC
At the moment one appears only to be able to search for one attribute at the time when searching for users in gamma (at least on the /users screen). It would be great to be able to search for (for example) 
* firstname lastname
* firstname year
* nick firstname

**Comment by Portals** [comment] 2020-05-11 14:35
Duplicate of #717

**Closed by Portals** 2020-05-11 14:35 UTC

**Comment by ViddeM** [comment] 2020-05-11 18:27
MB, I'm blind. 👍

**Comment by Portals** [comment] 2020-05-12 08:56
No problems, I renamed that issue to be more general than what I had earlier. So I sort of merged the two issues.
