### ISSUE TITLE
Cross origin resource sharing is disabled?

### ISSUE THREAD

**Issue by rosengrenen** [cthit/Gamma#613] opened 2020-04-07 22:00 UTC
Trying to get the access token from the token endpoint times out in a NodeJS server and gets a CORS error in the browser when trying to fetch from local React app

**Comment by Portals** [comment] 2020-04-09 06:13
Closing since this was caused by @rosengrenen accidentally calling production gamma (gamma.chalmers.it) instead of having a local version.

**Closed by Portals** 2020-04-09 06:13 UTC
